### ISSUE TITLE
Muting issue

### ISSUE THREAD

**Issue by genewm** [SoundControl/Issues#102]
After my system updated SoundControl yesterday (1/30/14) I found that when the commercials are muted and the music comes on it also is muted. I have to manually check and un-mute them. I have cleaned the cache and restarted Chrome with no change. Not sure if there is some setting that would change that. 

Thanks,
Gene

**Comment by SoundControl** [comment]
Gene,

What do you mean by "it also is muted"? Are you saying that it never
unmutes when a song comes on? There was a bug similar to this I have
confirmed was fixed by the last update, so this may be a new one.

1) Are you running windows?
2) Have you done a system restore recently?
3) Change a setting on the options page. Restart the browser. Is the
setting still correct (as the changed value)?

**Comment by genewm** [comment]
Scott,

Yes, it never unmutes.
I am running Windows 7.
No system restore.
Yes, after changing a value, mute to 5% for ads and restarting Chrome the settings remain.

Thanks,
Gene

**Comment by genewm** [comment]
Scott,

I have done the following:

Uninstalled SoundControl, cleaned out history and cache in Chrome and restarted it.
Reinstalled SoundControl.
The sound is muted after an ad even though it isn't set that way.
Changed settings in SoundControl to 10% ad volume but the sound stays muted after the ad is done.

OK, odd it just worked after restating it again... I have volume for ads at 10% and the music comes back correctly now... go figure.

Thanks,
Gene

**Comment by SoundControl** [comment]
For number 3) I was referring to any setting on the options page (not the
volume). Try changing the "art on button" setting and see if it stays.

**Comment by genewm** [comment]
OK, taking off the art fixed it without restarting the browser... Hmmmm.

**Comment by SoundControl** [comment]
Tracking this as #103
