### ISSUE TITLE
Link button to tab loaded with HTTPS

### ISSUE THREAD

**Issue by jarshwah** [SoundControl/Issues#157]
Not sure how feasible this is, but I usually open the pandora tab under HTTPS. The button isn't "linked" to that tab though, so it'll just launch a new https version. An option to open https://pandora would be aces.

**Comment by SndControl** [comment]
Josh,

We will look into this issue but it is probably not feasible for us to
develop a workaround for this issue right now. I anticipate this problem
may occur more often in the future but, right now, it's not prevalent among
our users.

Thank you for pointing this out and I assure you we will look at the issue
and if it is an easy fix, we will see what we can do. Most importantly, we
will put this on our radar and start planning for the future with solving
this problem in mind because it may become more common across web music
players in the near future. And you were the first one to point it out to
us. Thanks.

Also, we are going to be doing some testing on our new onboarding process
for new users in the coming month. If you have any interest in being in on
our testing aces team to help us smooth out the process, email me at
support@sndcontrol.com with your gmail and we'll send you an invite when we
are ready to start testing.

On Thu, Feb 26, 2015 at 7:21 PM, Josh Smeaton notifications@github.com
wrote:

> Not sure how feasible this is, but I usually open the pandora tab under
> HTTPS. The button isn't "linked" to that tab though, so it'll just launch a
> new https version. An option to open https://pandora would be aces.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoundControl/Issues/issues/157.

## 

Clay | SndControl
SoundControl Support Team
clayton@sndcontrol.com - Email
http://sndcontrol.com - Visit

**Comment by jarshwah** [comment]
I'm no longer personally interested in this. Feel free to reopen (or recreate) if still interested.
