### ISSUE TITLE
Integrate with Alfred for easier control

### ISSUE THREAD

**Issue by altryne** [SoundControl/Issues#55]
Hi,
I'm the developer of Alfred + Pandora
http://alexw.me/2013/03/controlling-pandora-com-from-alfred-2-and-media-keys/
After you asked me to remove your code, many people asked me if this going to be available again.
Please integrate something like controlling music from Alfred

**Comment by SoundControl** [comment]
Yep, I started on this, but it hasn't been completed since I got hung up on finding the limitations of the server that would be started by Alfred. Can you send me the command / script / settings that allow the temporary server to be started? I intend to make it compatible with a broader server control framework.

It'd be best to continue at issue #25
