### ISSUE TITLE
I had aleady paid for SoundControlPLus, but dont know how to get it

### ISSUE THREAD

**Issue by aaroo** [SoundControl/Issues#87]
Hi,

I really like your product, so I purchased soundControl Plus. However I don't now how to get it.

Culd you please let me know what I should do after that?

Thanks,

--Aru

**Comment by SoundControl** [comment]
Aru, I show that you have been active with Plus as of at least 17 hours
ago. Has this problem developed since then? You should be able to go to the
options page, click "plus" in the lower right corner and see your license
status. If you don't show a valid license, you can manually enter your key
by clicking the link in the lower left.

**Comment by aaroo** [comment]
I do not see that I have Plus. What is my key, and how could I enter it?

**Comment by SoundControl** [comment]
Replied privately
